package Perpustakaan;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class HomeAdmin extends javax.swing.JFrame {

    String URL_WITH_DB = "jdbc:mysql://localhost:3306/perpustakaan?autoReconnect=true&useSSL=false";
    Statement stmt = null;
    PreparedStatement ps = null;
    Connection conn = null;
    ResultSet rs;

    DefaultTableModel tabelModel;

    boolean statusEdit = false;
    int activeRow = 0;

    public HomeAdmin() {
        initComponents();
        tabelModel = new DefaultTableModel();
        tabelModel.addColumn("Book Code");
        tabelModel.addColumn("Book Title");
        tabelModel.addColumn("Author");
        tabelModel.addColumn("Synopsis");
        tabelModel.addColumn("Number of Pages");
        bukuTable.setModel(tabelModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfKodeBuku = new javax.swing.JTextField();
        tfJudulBuku = new javax.swing.JTextField();
        tfJmlHal = new javax.swing.JTextField();
        tfPengarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bDelete = new javax.swing.JButton();
        bAddUpdate = new javax.swing.JButton();
        bClear = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taSinopsis = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        bukuTable = new javax.swing.JTable();
        bShowBorrowList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 237, 219));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel1.setText("BOOK CODE :");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 30)); // NOI18N
        jLabel2.setText("MANAGE 3000 LIBRARY DATA");

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel3.setText("BOOK TITLE :");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel4.setText("AUTHOR :");

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel5.setText("SYNOPSIS :");

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel6.setText("NUMBER OF PAGES :");

        bDelete.setBackground(new java.awt.Color(102, 81, 61));
        bDelete.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        bDelete.setForeground(new java.awt.Color(255, 255, 255));
        bDelete.setText("Delete");
        bDelete.setEnabled(false);
        bDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeleteActionPerformed(evt);
            }
        });

        bAddUpdate.setBackground(new java.awt.Color(102, 81, 61));
        bAddUpdate.setForeground(new java.awt.Color(255, 255, 255));
        bAddUpdate.setText("Add");
        bAddUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddUpdateActionPerformed(evt);
            }
        });

        bClear.setBackground(new java.awt.Color(102, 81, 61));
        bClear.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        bClear.setForeground(new java.awt.Color(255, 255, 255));
        bClear.setText("Clear");
        bClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClearActionPerformed(evt);
            }
        });

        taSinopsis.setColumns(20);
        taSinopsis.setRows(5);
        jScrollPane2.setViewportView(taSinopsis);

        bukuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Book Code", "Book Title", "Author", "Synopsis", "Number of Pages"
            }
        ));
        bukuTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bukuTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(bukuTable);

        bShowBorrowList.setBackground(new java.awt.Color(102, 81, 61));
        bShowBorrowList.setForeground(new java.awt.Color(255, 255, 255));
        bShowBorrowList.setText("Lihat List Peminjaman");
        bShowBorrowList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bShowBorrowListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(181, 181, 181))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bShowBorrowList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bClear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bAddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(tfPengarang, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                            .addComponent(tfKodeBuku))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfJmlHal, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                        .addComponent(jLabel6)))
                                .addGap(32, 32, 32))
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(32, 32, 32))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfKodeBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfJudulBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfJmlHal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAddUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bShowBorrowList, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearInput() {
        tfKodeBuku.setText("");
        tfJudulBuku.setText("");
        tfPengarang.setText("");
        tfJmlHal.setText("");
        taSinopsis.setText("");
    }

    private void bAddUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddUpdateActionPerformed
        if (!statusEdit) {
            if (!tfKodeBuku.getText().equals("") && !tfJudulBuku.getText().equals("") && !tfPengarang.getText().equals("") && !tfJmlHal.getText().equals("") && !taSinopsis.getText().equals("")) {
                try {
                    conn = DriverManager.getConnection(URL_WITH_DB, "root", "");
                    stmt = conn.createStatement();
                    int hsl = stmt.executeUpdate("INSERT INTO buku " + "(kode_buku,judul,pengarang,sinopsis,jml_halaman) " + "VALUES ('" + tfKodeBuku.getText() + "', '" + tfJudulBuku.getText() + "', '" + tfPengarang.getText() + "', '" + taSinopsis.getText() + "', '" + tfJmlHal.getText() + "')");
                    stmt.close();
                    conn.close();
                    rs.close();
                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                }
                tabelModel.addRow(new Object[]{
                    tfKodeBuku.getText(),
                    tfJudulBuku.getText(),
                    tfPengarang.getText(),
                    taSinopsis.getText(),
                    tfJmlHal.getText()
                });
            } else {
                JOptionPane.showMessageDialog(null, "Isi semua data!");
            }
        } else {
            tabelModel.setValueAt(tfKodeBuku.getText(), activeRow, 0);
            tabelModel.setValueAt(tfJudulBuku.getText(), activeRow, 1);
            tabelModel.setValueAt(tfPengarang.getText(), activeRow, 2);
            tabelModel.setValueAt(taSinopsis.getText(), activeRow, 3);
            tabelModel.setValueAt(tfJmlHal.getText(), activeRow, 4);

            try {
                conn = DriverManager.getConnection(URL_WITH_DB, "root", "");
                stmt = conn.createStatement();
                rs = stmt.executeQuery("SELECT * FROM buku");
                if (rs.next()) {
                    String query = "UPDATE buku " + "SET kode_buku=?,judul=?,pengarang=?,sinopsis=?,jml_halaman=? WHERE id=" + rs.getInt("id");
                    ps = conn.prepareStatement(query);
                    ps.setString(1, tfKodeBuku.getText());
                    ps.setString(2, tfJudulBuku.getText());
                    ps.setString(3, tfPengarang.getText());
                    ps.setString(4, taSinopsis.getText());
                    ps.setString(5, tfJmlHal.getText());
                }
                JOptionPane.showMessageDialog(null, "Update success!");
                ps.executeUpdate();
                conn.close();
                stmt.close();
                ps.close();
                rs.close();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
            clearInput();
            bukuTable.clearSelection();
            statusEdit = false;
            bAddUpdate.setText("Update");
            tfKodeBuku.requestFocus();
        }
        bDelete.setEnabled(false);
    }//GEN-LAST:event_bAddUpdateActionPerformed

    private void bClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClearActionPerformed
        bukuTable.clearSelection();
        clearInput();
        tfKodeBuku.requestFocus();
        statusEdit = false;
        bAddUpdate.setText("Add");
        bDelete.setEnabled(false);
    }//GEN-LAST:event_bClearActionPerformed

    private void bDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeleteActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Are you sure ?") == JOptionPane.OK_OPTION) {
            try {
                conn = DriverManager.getConnection(URL_WITH_DB, "root", "");
                stmt = conn.createStatement();
                rs = stmt.executeQuery("SELECT * FROM buku");
                while (rs.next()) {
                    int id = rs.getInt("id");
                    String kode = rs.getString("kode_buku");
                    if (id == id && tfKodeBuku.getText().equals(kode)) {
                        String query = "DELETE FROM buku WHERE id=" + id;
                        ps = conn.prepareStatement(query);
                    }
                }
                ps.executeUpdate();
                conn.close();
                stmt.close();
                ps.close();
                rs.close();
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
            tabelModel.removeRow(activeRow);
            clearInput();
            statusEdit = false;
            bAddUpdate.setText("Add");
            bDelete.setEnabled(false);
        }
    }//GEN-LAST:event_bDeleteActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(URL_WITH_DB, "root", "");
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT * FROM buku");

            while (rs.next()) {
                String kode = rs.getString("kode_buku");
                String judul = rs.getString("judul");
                String pengarang = rs.getString("pengarang");
                String sinopsis = rs.getString("sinopsis");
                String jml = String.valueOf(rs.getInt("jml_halaman"));

                String bukuTbl[] = {kode, judul, pengarang, sinopsis, jml};

                tabelModel.addRow(bukuTbl);
            }
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_formComponentShown

    private void bukuTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bukuTableMouseClicked
        int row = bukuTable.getSelectedRow();
        if (row != -1) {
            String code = bukuTable.getValueAt(row, 0).toString();
            String title = bukuTable.getValueAt(row, 1).toString();
            String author = bukuTable.getValueAt(row, 2).toString();
            String synopsis = bukuTable.getValueAt(row, 3).toString();
            String pages = bukuTable.getValueAt(row, 4).toString();
            tfKodeBuku.setText(code);
            tfJudulBuku.setText(title);
            tfPengarang.setText(author);
            taSinopsis.setText(synopsis);
            tfJmlHal.setText(pages);
            statusEdit = true;
            bAddUpdate.setText("Update");
            bDelete.setEnabled(true);
            activeRow = row;
        }
    }//GEN-LAST:event_bukuTableMouseClicked

    private void bShowBorrowListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bShowBorrowListActionPerformed
        new BorrowList().setVisible(true);
    }//GEN-LAST:event_bShowBorrowListActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddUpdate;
    private javax.swing.JButton bClear;
    private javax.swing.JButton bDelete;
    private javax.swing.JButton bShowBorrowList;
    private javax.swing.JTable bukuTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea taSinopsis;
    private javax.swing.JTextField tfJmlHal;
    private javax.swing.JTextField tfJudulBuku;
    private javax.swing.JTextField tfKodeBuku;
    private javax.swing.JTextField tfPengarang;
    // End of variables declaration//GEN-END:variables
}
